{% set name = "semsimian" %}
{% set version = "0.2.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/monarch-initiative/semsimian/archive/v{{ version }}.tar.gz
  sha256: 4f0c97348d6cadc21a7f613b68ef5c11038e7bfd61ac8e069d11bf7f459c80b6

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=0.14,<0.15
    - pip
  run:
    - python
test:
  imports:
    - semsimian
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/monarch-initiative/semsimian
  summary: Semsimian is a package to provide fast semantic similarity calculations for ontologies. It is a Rust library with a Python interface. This includes implementation of Jaccard and Resnik similarity of terms in an ontology, as well as a method to calculate the similarity of two sets of terms (so-called termset similarity).
    Other methods will be added in the future.
  license: BSD-3-Clause
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - dillonroach
